# Generated by Django 5.2.12 on 2026-04-10 20:10

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('carrier_type', models.CharField(max_length=30)),
                ('subtype', models.CharField(blank=True, max_length=30)),
                ('orientation', models.CharField(default='horizontal', max_length=20)),
                ('unit', models.CharField(default='mm', max_length=20)),
                ('offset_x_mm', models.PositiveIntegerField(default=0)),
                ('offset_y_mm', models.PositiveIntegerField(default=0)),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('host_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_carriers', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
                'ordering': ('host_device', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeviceTypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('hosts_carriers', models.BooleanField(default=False)),
                ('internal_width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('internal_height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('internal_depth_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('mountable_on', models.CharField(blank=True, max_length=30)),
                ('mountable_subtype', models.CharField(blank=True, max_length=30)),
                ('footprint_primary', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('footprint_secondary', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('device_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_profile', to='dcim.devicetype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Device Type Profile',
                'verbose_name_plural': 'Device Type Profiles',
                'ordering': ('device_type',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('position_x', models.PositiveIntegerField(blank=True, null=True)),
                ('position_y', models.PositiveIntegerField(blank=True, null=True)),
                ('size_x', models.PositiveIntegerField(blank=True, null=True)),
                ('size_y', models.PositiveIntegerField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to='netbox_cabinet_view.carrier')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_mounts', to='dcim.device')),
                ('device_bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_mounts', to='dcim.devicebay')),
                ('module_bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_mounts', to='dcim.modulebay')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Mount',
                'verbose_name_plural': 'Mounts',
                'ordering': ('carrier', 'position', 'position_x', 'position_y'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device',), name='unique_mount_device'), models.UniqueConstraint(condition=models.Q(('device_bay__isnull', False)), fields=('device_bay',), name='unique_mount_device_bay'), models.UniqueConstraint(condition=models.Q(('module_bay__isnull', False)), fields=('module_bay',), name='unique_mount_module_bay')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
