# Generated by Django 5.2.12 on 2026-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cabinet_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='row_height_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='rows',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='row',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mount',
            name='row_span',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='mount',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
