# Generated by Django 5.2.13 on 2026-07-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cabinet_view', '0008_port_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemountprofile',
            name='rear_image',
            field=models.ImageField(blank=True, upload_to='devicetype-images'),
        ),
        migrations.AddField(
            model_name='devicemountprofile',
            name='rear_port_map',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modulemountprofile',
            name='rear_image',
            field=models.ImageField(blank=True, upload_to='moduletype-images'),
        ),
        migrations.AddField(
            model_name='modulemountprofile',
            name='rear_port_map',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
